spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taz_book_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    mail:
        host: localhost
        port: 1025
        protocol: smtp
        username: ""
        password: ""
        properties:
          mail:
            smtp:
              trust: "*"
            auth: true
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000